# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_analyser.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13text_analyser.proto\"\x1f\n\x0f\x41nalysisRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\xce\x01\n\x10\x41nalysisResponse\x12\x43\n\x12words_by_frequency\x18\x01 \x03(\x0b\x32\'.AnalysisResponse.WordsByFrequencyEntry\x12\x1b\n\x13\x61verage_word_length\x18\x02 \x01(\x02\x12\x1f\n\x17\x61verage_sentence_length\x18\x03 \x01(\x02\x1a\x37\n\x15WordsByFrequencyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x16\n\x14GetStatisticsRequest\"\xd8\x01\n\x15GetStatisticsResponse\x12H\n\x12words_by_frequency\x18\x01 \x03(\x0b\x32,.GetStatisticsResponse.WordsByFrequencyEntry\x12\x1b\n\x13\x61verage_word_length\x18\x02 \x01(\x02\x12\x1f\n\x17\x61verage_sentence_length\x18\x03 \x01(\x02\x1a\x37\n\x15WordsByFrequencyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xca\x01\n\x0eStorageRequest\x12\x41\n\x12words_by_frequency\x18\x01 \x03(\x0b\x32%.StorageRequest.WordsByFrequencyEntry\x12\x1b\n\x13\x61verage_word_length\x18\x02 \x01(\x02\x12\x1f\n\x17\x61verage_sentence_length\x18\x03 \x01(\x02\x1a\x37\n\x15WordsByFrequencyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\"\n\x0fStorageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\x13TextAnalyserService\x12\x32\n\x0b\x41nalyseText\x12\x10.AnalysisRequest\x1a\x11.AnalysisResponse2\x90\x01\n\x18StatisticsStorageService\x12\x34\n\x0fStoreStatistics\x12\x0f.StorageRequest\x1a\x10.StorageResponse\x12>\n\rGetStatistics\x12\x15.GetStatisticsRequest\x1a\x16.GetStatisticsResponse2S\n\x11WebDisplayService\x12>\n\rGetStatistics\x12\x15.GetStatisticsRequest\x1a\x16.GetStatisticsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_analyser_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANALYSISRESPONSE_WORDSBYFREQUENCYENTRY._options = None
  _ANALYSISRESPONSE_WORDSBYFREQUENCYENTRY._serialized_options = b'8\001'
  _GETSTATISTICSRESPONSE_WORDSBYFREQUENCYENTRY._options = None
  _GETSTATISTICSRESPONSE_WORDSBYFREQUENCYENTRY._serialized_options = b'8\001'
  _STORAGEREQUEST_WORDSBYFREQUENCYENTRY._options = None
  _STORAGEREQUEST_WORDSBYFREQUENCYENTRY._serialized_options = b'8\001'
  _ANALYSISREQUEST._serialized_start=23
  _ANALYSISREQUEST._serialized_end=54
  _ANALYSISRESPONSE._serialized_start=57
  _ANALYSISRESPONSE._serialized_end=263
  _ANALYSISRESPONSE_WORDSBYFREQUENCYENTRY._serialized_start=208
  _ANALYSISRESPONSE_WORDSBYFREQUENCYENTRY._serialized_end=263
  _GETSTATISTICSREQUEST._serialized_start=265
  _GETSTATISTICSREQUEST._serialized_end=287
  _GETSTATISTICSRESPONSE._serialized_start=290
  _GETSTATISTICSRESPONSE._serialized_end=506
  _GETSTATISTICSRESPONSE_WORDSBYFREQUENCYENTRY._serialized_start=208
  _GETSTATISTICSRESPONSE_WORDSBYFREQUENCYENTRY._serialized_end=263
  _STORAGEREQUEST._serialized_start=509
  _STORAGEREQUEST._serialized_end=711
  _STORAGEREQUEST_WORDSBYFREQUENCYENTRY._serialized_start=208
  _STORAGEREQUEST_WORDSBYFREQUENCYENTRY._serialized_end=263
  _STORAGERESPONSE._serialized_start=713
  _STORAGERESPONSE._serialized_end=747
  _TEXTANALYSERSERVICE._serialized_start=749
  _TEXTANALYSERSERVICE._serialized_end=822
  _STATISTICSSTORAGESERVICE._serialized_start=825
  _STATISTICSSTORAGESERVICE._serialized_end=969
  _WEBDISPLAYSERVICE._serialized_start=971
  _WEBDISPLAYSERVICE._serialized_end=1054
# @@protoc_insertion_point(module_scope)
